def even_fib(n):
    '''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed
    four million, find the sum of the even-valued terms.

    >>> even_fib(231)
    188
    >>> even_fib(3)
    2
    >>> even_fib(6)
    10
    >>> even_fib(4000000)
    4613732
    '''

    curr, prev, total_evens = 1, 0, 0
    while prev < n:
        curr, prev = prev, curr + prev
        if prev % 2 == 0:
            total_evens += prev
    return total_evens
